locale: "en-US"
title: "Guang Cheng"
title_separator: "-"
name: "Guang Cheng"
description: "Guang's personal website"
url: "https://gcheng.org"
baseurl: ""

include:
  - _pages

exclude:
  - Gemfile
  - node_modules
  - tmp
  - vendor

markdown: kramdown
kramdown:
  input: GFM

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
