locale: "en-US"
title: "Guang Cheng"
title_separator: "-"
name: "Guang Cheng"
description: "Ph.D. candidate in Operations Research and Analytics at the National University of Singapore."
url: "https://gcheng-nus.github.io"
baseurl: ""

include:
  - _pages

exclude:
  - Gemfile
  - LICENSE
  - node_modules
  - tmp
  - vendor

markdown: kramdown
kramdown:
  input: GFM

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
